-- boardgame-v1 SQLite schema
-- Version: v1.0.0
-- Generated by F5-DBA (2026-03-21)
-- Engine: E-FACTORY / AQ-001

PRAGMA journal_mode = WAL;
PRAGMA foreign_keys = ON;

-- ─────────────────────────────────────────
-- games: 게임 세션 단위
-- ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS games (
    game_id       TEXT    PRIMARY KEY,           -- UUID v4
    created_at    REAL    NOT NULL,              -- Unix timestamp
    num_players   INTEGER NOT NULL CHECK (num_players BETWEEN 2 AND 6),
    board_size    INTEGER NOT NULL DEFAULT 20,
    status        TEXT    NOT NULL DEFAULT 'in_progress'
                          CHECK (status IN ('in_progress', 'completed', 'abandoned')),
    winner_player_id INTEGER,                   -- 0-based index, NULL until game ends
    total_turns   INTEGER DEFAULT 0,
    ended_at      REAL                          -- NULL until game ends
);

-- ─────────────────────────────────────────
-- game_players: 게임 내 플레이어 등록
-- ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS game_players (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    game_id       TEXT    NOT NULL REFERENCES games(game_id) ON DELETE CASCADE,
    player_id     INTEGER NOT NULL CHECK (player_id >= 0),
    player_name   TEXT    NOT NULL DEFAULT 'Player',
    final_position INTEGER,                     -- NULL until game ends
    final_rank    INTEGER,                      -- 1=winner, NULL if in_progress
    UNIQUE (game_id, player_id)
);

-- ─────────────────────────────────────────
-- moves: 이동 이력 (audit trail)
-- ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS moves (
    move_id       INTEGER PRIMARY KEY AUTOINCREMENT,
    game_id       TEXT    NOT NULL REFERENCES games(game_id) ON DELETE CASCADE,
    player_id     INTEGER NOT NULL,
    turn_number   INTEGER NOT NULL,
    dice_roll     INTEGER NOT NULL CHECK (dice_roll BETWEEN 1 AND 6),
    old_position  INTEGER NOT NULL,
    new_position  INTEGER NOT NULL,
    is_win        INTEGER NOT NULL DEFAULT 0 CHECK (is_win IN (0, 1)),
    recorded_at   REAL    NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_moves_game_id ON moves (game_id);
CREATE INDEX IF NOT EXISTS idx_moves_player ON moves (game_id, player_id);

-- ─────────────────────────────────────────
-- game_saves: 세이브 슬롯 (일시정지/재개)
-- ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS game_saves (
    save_id       INTEGER PRIMARY KEY AUTOINCREMENT,
    game_id       TEXT    NOT NULL REFERENCES games(game_id) ON DELETE CASCADE,
    session_token TEXT    NOT NULL UNIQUE,      -- browser sessionStorage key
    board_snapshot TEXT   NOT NULL,             -- JSON from Board.state_snapshot()
    saved_at      REAL    NOT NULL
);

-- ─────────────────────────────────────────
-- leaderboard: 플레이어 집계 통계
-- ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS leaderboard (
    player_name   TEXT    PRIMARY KEY,
    wins          INTEGER NOT NULL DEFAULT 0,
    games_played  INTEGER NOT NULL DEFAULT 0,
    total_moves   INTEGER NOT NULL DEFAULT 0,   -- all moves across all games
    best_win_turns INTEGER,                     -- minimum turn count to win (NULL if never won)
    last_played   REAL                          -- Unix timestamp of last game
);

-- ─────────────────────────────────────────
-- Views
-- ─────────────────────────────────────────

CREATE VIEW IF NOT EXISTS v_leaderboard AS
SELECT
    player_name,
    wins,
    games_played,
    CASE WHEN games_played > 0
         THEN ROUND(wins * 100.0 / games_played, 1)
         ELSE 0.0 END AS win_rate_pct,
    ROUND(CASE WHEN wins > 0
               THEN total_moves * 1.0 / wins
               ELSE NULL END, 1) AS avg_moves_per_win,
    best_win_turns,
    last_played
FROM leaderboard
ORDER BY wins DESC, win_rate_pct DESC;
